### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [Atvaark/W3SavegameEditor#3]
Hi, 

thank you so much for this tool.
I've a question, I'm not so familiar with programming, I was looking for a tool to mark one of my quests as completed insted of failed (happend due to a bug, the quest is completed but it's marked failed)

Can your tool do that?
Would be awesome if you could help me quick.

thank you so much!

**Comment by Atvaark** [comment]
Hey,

sorry but that isn't possible with this tool. Someone would have to figure out which values have to be changed to mark the quest as completed. When that's figured out someone has to write the code to insert the new values into your savegame.

You should check if the developer console can somehow edit your quest progress.

**Comment by ghost** [comment]
:( do you know how to do it in developer console? do you have a mail address so we can talk?

**Comment by saltydk** [comment]
You may want to look here:
http://forums.cdprojektred.com/threads/39932-Spoiler-Favor-for-Radovid-did-not-activate?p=2006430&viewfull=1#post2006430

However, it is a complicated process to edit a quest if it has dependencies down the road. If certain flags are checked in a later quest the changed quest may still end up being flagged as failed due to missing "sub flags" or whatever you want to call them. I have yet to find a good way to gain any insight into their structure.

**Comment by Atvaark** [comment]
Closed due to inactivity.
